### ISSUE TITLE
Does this library support mocking the virtual function or only non-virtual ones?

### ISSUE THREAD

**Issue by vesavlad** [mazong1123/injectorpp#13]
This library is very similar to cppfreemock. I'm wondering if I can mock virtual methods using your library because using cppfreemock this has been proven to be imposible.

I am wondering how much work there is to port this library to linux env because if it supports the mocking of virtual function It would be very very interesting to use.

I would also would like to spent some time on extending it's functionality if you can confirm that mocking virtual methods should be possible.

**Comment by mazong1123** [comment]
I'm still investigating so I'm not going to confirm virtual methods mocking at this time. However, it would be possible on Windows as InjectorPP retrieving info from .pdb file. Think about the Visual C++ debugger. We can change variable values, step over methods (both virtual or non-virtual member functions). I'm still working on this feature, but theoretically it should be possible. 

For Linux, I haven't started my investigation yet. However, I can tell we're able to leverage ptrace to implement almost all features except mocking virtual methods - as we don't know the address at compile time. We still need a debugger specific solution. For instance, with -g option, gdb is able to step in & step over virtual or non-virtual functions. That should be the way to achieve our goal.

The work load to port this library to linux should be huge. As I'm using debugger specific info (.pdb) on Windows. Although we can keep the interfaces, the core logic should be rewritten by leveraging ptrace and debugger specific info on Linux.

**Comment by vesavlad** [comment]
Yeah you're right about virtual methods.

I did some research on my own and the only solution to mock the virtual methods, in my opinion is the following one:

- you must receive the exact object type that you want to mock, and the method that you want to mock
- the "library , InjectorPP" should instantiate an object of the received type, just to have the vtable in order to be able to determine the real method address.
- then, using the address received (this should be the id in the vtable) we should be able to find the real method address assigned by the compiler. 
- then the mocking procedure should follow the same pattern as you currently do for non virtual methods

Regarding the port to linux, I have in mind a solution that currently is working with cppfreemock

**Comment by mazong1123** [comment]
Just added the support for mocking virtual methods . It's not perfect yet, but works in most cases. Just leveraged the pdb file for retrieving virtual method name from address so it's a compiler specified implementation.

**Comment by mazong1123** [comment]
Closing it as we have already supported virtual method.
